name: Test Python

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Vérifier la syntaxe
        run: python -m py_compile analyse_logs.py
